language: php
php:
  - "5.5"
  - "5.4"
  
before_script: 
  - composer install
  
script:
  - bin/behat
  - bin/phpunit
  - bin/phpcs src/ test/src/ --standard=vendor/instaclick/symfony2-coding-standard/Symfony2
  
